services:
  redis_db:
    image: redis
    container_name: redis_db
    restart: always
    volumes:
      - redis_data:/data


  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "1993:1993"
    env_file:
      - ./server/.env
    command: node dist/index.js


  workers:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: workers
    restart: always
    env_file:
      - ./server/.env
    command: node dist/workers/init.js


volumes:
  redis_data: