export const ENV = {
  API_ENDPOINT: process.env.NEXT_PUBLIC_BASE_URL,
  RAZORPAY_KEY: process.env.NEXT_PUBLIC_RAZORPAY_KEY,
  STRIPE_PUBLISHABLE_KEY: process.env.NEXT_STRIPE_PUBLISHABLE_KEY,
  PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL
}